*** Variables ***
${REMOTE_URL}     %{REMOTE_URL}
${AUTOMATION_NAME}    XCUITest
${PLATFORM_NAME}    iOS
${PLATFORM_VERSION}    %{PLATFORM_VERSION}
${DEVICE_NAME}    %{DEVICE_NAME}
${APP_LOCATION}     %{APP_LOCATION}


